baseURL = "https://haytok.jp/"
title = "haytok's Website"
theme = "manis-hugo-theme"
publishDir = "docs"
canonifyurls = true

# Copyright notice. Note: You can use HTML tag here
copyright = "&copy; 2021 haytok"
pluralizeListTitles = false

# Minimum number of posts before paginate navigation show up
[pagination]
  pagerSize = 10

# Your disqus shortname
disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

# Google Analytics
googleAnalytics = 'G-YXCYPL25QW'

[menu]
	[[menu.main]]
		name = "Post"
		url = "/post"
	
	[[menu.main]]
		name = "About"
		url = "/about"
	[[menu.main]]
		name = "Scraps"
		url = "/scraps"
	[[menu.main]]
		name = "Log"
		url = "/log"
	[[menu.main]]
		name = "Tags"
		url = "/tags"

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = ["/css/main.css"]
	
	# Site meta description
	description = "haytok's Website."
	# Site's Tagline (Subtitle or Keyword)
	tagline = "Welcome to my website !"
	# If true give attribution to this theme
	themeAttrib = true
	# URL to license file, can be outside of your domain
	# licenseURL = "/about/license"

	# Configure which sections for Latest Posts
	mainSections = ["blog", "post"]
	# Configure which sections for Latest Works
	# works は基本的には表示しない。
	# workSections = ["work"]
	
	# List of sections that support disqus comments
	disqusSections = [ "blog" ]
	# List of sections that support utterances comments
	utterancesSections = [ "blog" ]
	
	# Utterances Configuration
	utterancesRepo = ""
	utterancesTheme = "github-light"
	utterancesLabel = ""

	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#e47911"
	# Maximum number of item in Latest Posts or Works
	latestCount = 5
	# Path to site's favicon image
	faviconImg = "/img/images/favicon.ico"
	images = [""]
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = false
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	# email = "mail@yurizal-san.com"
	github = "https://github.com/haytok"
	twitter = "https://twitter.com/haytok6"
	# blog = "https://dilmnqvo.hatenablog.com"

# Language Configuration
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1

[markup.goldmark.renderer]
	unsafe= true
